// export const DATABASE_STRATEGY = 'database_strategy';
// export const ORM_STRATEGY = 'orm_strategy';
// export const POSTGRES_URL = 'postgres_url';
// export const MONGO_URL = 'mongo_url';
// export const SQLITE_URL = 'sqlite_url';

export enum EUserRole {
	ADMIN     = 'ADMIN',
	MANAGER   = 'MANAGER',
	FIELD_REP = 'FIELD_REP',
}



export enum EOrganizationStatus {
	ACTIVE      = 'ACTIVE',
	TRIAL       = 'TRIAL',
	SUSPENDED   = 'SUSPENDED',
	DEACTIVATED = 'DEACTIVATED',
}



export enum ESubscriptionStatus {
	VALID   = 'VALID',
	EXPIRED = 'EXPIRED',
}



export enum EPaymentStatus {
	PENDING  = 'PENDING',
	PAID     = 'PAID',
	VERIFIED = 'VERIFIED',
	REFUNDED = 'REFUNDED',
}



export enum ESaleStatus {
	DRAFT     = 'DRAFT',
	SYNCED    = 'SYNCED',
	CANCELLED = 'CANCELLED',
}



export enum EAccountStatus {
	ACTIVE      = 'ACTIVE',
	DEACTIVATED = 'DEACTIVATED',
	UNVERIFIED  = 'UNVERIFIED',
}



export enum EEnvVars {
	NODE_ENV                   = 'NODE_ENV',
	POSTGRES_URL               = 'POSTGRES_URL',
	SQLITE_URL                 = 'SQLITE_URL',
	LOGGER_STRATEGY            = 'LOGGER_STRATEGY',
	DATABASE_STRATEGY          = 'DATABASE_STRATEGY',
	ORM_STRATEGY               = 'ORM_STRATEGY',
	POSTGRES_USERNAME          = 'POSTGREST_USERNAME',
	POSTGRES_PASSWORD          = 'POSTGRES_PASSWORD',
	PADDLE_PRODUCTION_API_KEY  = 'PADDLE_PRODUCTION_API_KEY',
	PADDLE_DEVELOPMENT_API_KEY = 'PADDLE_DEVELOPMENT_API_KEY',
	JWT_SECRET_KEY             = 'JWT_SECRET_KEY',
}



export enum ENodeEnv {
	DEVELOPMENT = 'DEVELOPMENT',
	PRODUCTION  = 'PRODUCTION',
	TEST        = 'TEST',
}



export enum EDatabaseStrategy {
	POSTGRES = 'POSTGRES',
	SQLITE   = 'SQLITE',
}



export enum EOrmStrategy {
	DRIZZLE = 'DRIZZLE',
}



export enum ELoggerStrategy {
	CONSOLE = 'CONSOLE',
	WINSTON = 'WINSTON',
}



export enum EActivityType {
	SALE_INITIALIZED  = 'SALE_INITIALIZED',
	SALE_CLOSED       = 'SALE_CLOSED',
	SALE_PROSPECTED   = 'SALE_PROSPECTED',
	DAY_OFF_REQUESTED = 'DAY_OFF_REQUESTED',
	REPORTED          = 'REPORTED',
	DATA_SYNCED       = 'DATA_SYNCED',
	LOGGED_OFF        = 'LOGGED_OFF',
	LOGGED_IN         = 'LOGGED_IN',
	PAYMENT_ADDED     = 'PAYMENT_ADDED',
	CLIENT_ADDED      = 'CLIENT_ADDED',
	CLIENT_UPDATED    = 'CLIENT_UPDATED',
	ITEM_ADDED        = 'ITEM_ADDED',
	ITEM_UPDATED      = 'ITEM_UPDATED',
	CHECK_IN          = 'CHECK_IN',
	CHECK_OUT         = 'CHECK_OUT',
	BREAK_STARTED     = 'BREAK_STARTED',
	BREAK_ENDED       = 'BREAK_ENDED',
	TRAVEL_STARTED    = 'TRAVEL_STARTED',
	TRAVEL_ENDED      = 'TRAVEL_ENDED',
	MEETING_ATTENDED  = 'MEETING_ATTENDED',
	TASK_COMPLETED    = 'TASK_COMPLETED',
	REPORT_SUBMITTED  = 'REPORT_SUBMITTED',
	EXPENSE_SUBMITTED = 'EXPENSE_SUBMITTED',
	ERROR_OCCURRED    = 'ERROR_OCCURRED',
	LEAVE_APPROVED    = 'LEAVE_APPROVED',
	LEAVE_REJECTED    = 'LEAVE_REJECTED',
	EXPENSE_APPROVED  = 'EXPENSE_APPROVED',
	EXPENSE_REJECTED  = 'EXPENSE_REJECTED',
	SALARY_PAID       = 'SALARY_PAID',
	PROFILE_UPDATED   = 'PROFILE_UPDATED',
	PASSWORD_CHANGED  = 'PASSWORD_CHANGED',
	NOTIFICATION_SENT = 'NOTIFICATION_SENT',
	DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
	INVENTORY_CHECKED = 'INVENTORY_CHECKED',
}
