name: Deployment

on:
  push:
    branches:
      - production

jobs:
  build-application:
    environment: production
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Pnpm
        run: npm i -g pnpm@latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build Image
        run: "docker build -t ghcr.io/${{github.actor}}/vantage_api:v0.1 ."

      - name: Login to GitHub Registry
        run: "echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin"

      - name: Push Image to Github Registry
        run: "docker push ghcr.io/${{github.actor}}/vantage_api:v0.1"
