name: Test Source
on:
  push:
    branches:
      - main

env:
  NODE_ENV: ${{vars.NODE_ENV}}
  POSTGRES_DATABASE_URL: ${{DATABASE_URL}}
  ORM_STRATEGY: ${{vars.ORM_STRATEGY}}
  DATABASE_STRATEGY: ${{vars.DATABASE_STRATEGY}}

jobs:
  test_units:
    environment: test
    name: Testing Project Units
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v6

      - name: Install pnpm
        run: npm i -g pnpm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Run unit test
        run: pnpm run test